---
- hosts: demosdn
  user: root
  vars:
    base_dir: "{{ BASE_DIR|default('/root/sc/ansible/') }}"
    prereq_file: '/var/tmp/.pre_req'

  tasks:
       - stat: path={{ prereq_file }}
         register: prereq
  
       - fail: msg="Please, run pre-req script before"
         when: prereq.stat.exists == False
  
        - name: Install virt and compilation tools commands and coCentOS or RedHat
          yum: name={{ item }} state=present
          with_items:
                - epel
                - git
                - "@virt*"
                - virt-manager
                - libguestfs-tools
                - bridge-utils
                - make
                - gcc
                - openssl-devel
                - autoconf
                - automake
                - rpm-build
                - python-devel
                - openssl-devel
                - kernel-devel 
                - kernel-debug-devel 
                - libtool
          when: ansible_distribution == "CentOS"

        - name: Install virt tools and openvswitch commands Ubuntu or Debian
          apt: name={{ item }} state=present
          with_items:
                - git
                - qemu-kvm
                - libvirt-bin
                - ubuntu-vm-builder
                - virtinst
                - bridge-utils
                - make
                - gcc
                - openssl-devel
                - autoconf
                - automake
          when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
                   
        - name: 
          




